### ISSUE TITLE
npm not finding file dist/index.js

### ISSUE THREAD

**Issue by LiamThys** [janeirodigital/sai-impl-service#12]
When doing npm install, npm is not able to find file dist/index.js. 

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path \node_modules\@janeirodigital\sai-impl-service\dist\index.js
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod \node_modules\@janeirodigital\sai-impl-service\dist\index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by elf-pavlik** [comment]
this package is not yet published to npm, where do you install it from?

**Comment by LiamThys** [comment]
I install it with git+https://github.com/janeirodigital/sai-impl-service.git.

**Comment by angelaraya** [comment]
My guess is that installing through git does not build the package as it does when publishing through NPM. Check if there is a `dist` folder in `node_modules/@janeirodigital/sai-server`. If not then that is the case and you need to build the package manually. I'd recommend using `npm link` until the package is stable and published officially. Closing but feel free to open again if needed.
