### ISSUE TITLE
Merge all packages into sai-js monorepo

### ISSUE THREAD

**Issue by elf-pavlik** [janeirodigital/sai-impl-service#81]
It will be easier to work if we have all the packages in the same monorepo. Sometimes when we move fast we need to manually `yarn link` between the two monorepos.

I would also like to start transitioning sai-js tests from the snippets in https://github.com/solid/data-interoperability-panel/ to the ones in css-storage-fixture in this repo.

**Comment by angelaraya** [comment]
Does this include the sai-impl-web? I'm keen to do it.

**Comment by elf-pavlik** [comment]
Nope, just sai-impl-service
